backoffice/src/main/java/uy/viruscontrol/backoffice/dto/DTOCasesQuantities.java
package uy.viruscontrol.backoffice.dto;

import java.io.Serializable;
import lombok.Data;

@Data
public class DTOCasesQuantities implements Serializable {
  private Long suspectTotal = 0L;
  private Long curedTotal = 0L;
  private Long confirmedTotal = 0L;
}

backoffice/src/main/java/uy/viruscontrol/backoffice/DashBean.java
package uy.viruscontrol.backoffice;

import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import lombok.Data;

@Named
@SessionScoped
@Data
public class DashBean implements Serializable {
  private String page = "graphs.xhtml";
}

backoffice/src/main/java/uy/viruscontrol/backoffice/DataSourceTypeBean.java
package uy.viruscontrol.backoffice;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import lombok.Getter;
import lombok.Setter;
import uy.viruscontrol.business.service.InformationSourceTypeService;
import uy.viruscontrol.common.dto.DTOInformationSourceType;
import uy.viruscontrol.common.exceptions.VirusControlException;

@Named
@ViewScoped
@Getter
@Setter
public class DataSourceTypeBean implements Serializable {
  @EJB
  private InformationSourceTypeService dataSourceTypeService;

  private DTOInformationSourceType dtoDataSourceType = new DTOInformationSourceType();
  private DTOInformationSourceType selectedDataSourceTypeUpdate = new DTOInformationSourceType();
  private DTOInformationSourceType selectedDataSourceTypeView = new DTOInformationSourceType();
  private List<DTOInformationSourceType> dataSourceTypes = new ArrayList<>();
  private String status = "";

  @PostConstruct
  public void init() {
    dataSourceTypes = dataSourceTypeService.getInformationSourceTypes(null);
  }

  public void handleBooleanChange() {
    FacesContext
      .getCurrentInstance()
      .addMessage(
        null,
        new FacesMessage(
          "Operacion relizada correctamente",
          selectedDataSourceTypeUpdate.getActive()
            ? "El tipo de fuente ha sido actualizado a activo"
            : "El tipo de fuente ha sido actualizado a inactivo"
        )
      );
  }

  public String activeTextBadge(Boolean isActive) {
    return isActive ? "Activa" : "Inactiva";
  }

  public String activeTextButton(Boolean isActive) {
    return isActive ? "Desactivar" : "Activar";
  }

  public String handleButtonStyleChange(Boolean isActive) {
    return isActive ? "blue-grey" : "blue-grey lighten-3";
  }

  public void setInformationSourceTypeStatus() {
    try {
      dataSourceTypeService.setInformationSourceTypeStatus(selectedDataSourceTypeUpdate.getId(), !selectedDataSourceTypeUpdate.getActive());
      handleBooleanChange();
      dataSourceTypes
        .stream()
        .filter(dtoInformationSourceType -> dtoInformationSourceType.getId().equals(selectedDataSourceTypeUpdate.getId()))
        .findFirst()
        .ifPresent(item -> item.setActive(!selectedDataSourceTypeUpdate.getActive()));
    } catch (VirusControlException virusControlException) {
      FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Ocurrio un error.", null));
    }
  }
}

backoffice/src/main/java/uy/viruscontrol/backoffice/NavigationBean.java
package uy.viruscontrol.backoffice;

import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import lombok.Data;

@Named
@SessionScoped
@Data
public class NavigationBean implements Serializable {
  private String page = "dashboard.xhtml";
  private Boolean logged = false;
}

backoffice/src/main/java/uy/viruscontrol/backoffice/RequestNewDiseaseBean.java
package uy.viruscontrol.backoffice;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import lombok.Getter;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;
import uy.viruscontrol.business.service.DiseaseService;
import uy.viruscontrol.business.service.ResourceService;
import uy.viruscontrol.business.service.SymptomService;
import uy.viruscontrol.common.dto.DTODisease;
import uy.viruscontrol.common.dto.DTOResource;
import uy.viruscontrol.common.dto.DTOSymptom;
import uy.viruscontrol.common.enumerations.EnumInfectiousAgentType;
import uy.viruscontrol.common.exceptions.VirusControlException;

@Named
@RequestScoped
@Getter
@Setter
@Slf4j
public class RequestNewDiseaseBean implements Serializable {
  @EJB
  private DiseaseService diseaseService;

  @EJB
  private SymptomService symptomService;

  @EJB
  private ResourceService resourcesService;

  private String diseaseName;
  private Long infectionTime;
  private String symptomName;
  private String symptomDescription;
  private String agentName;
  private EnumInfectiousAgentType agentType;
  private List<String> agentTypes = new ArrayList<>();
  private List<DTOSymptom> symptoms = new ArrayList<>();
  private List<DTOSymptom> selectedSymptoms = new ArrayList<>();
  private List<DTOResource> resources;
  private List<DTOResource> selectedResources = new ArrayList<>();

  @PostConstruct
  public void init() {
    loadSymptoms();
    listAgentTypes();
    loadResources();
  }

  public void listAgentTypes() {
    for (EnumInfectiousAgentType item : EnumInfectiousAgentType.values()) {
      agentTypes.add(capitalize(item.name()));
    }
  }

  public EnumInfectiousAgentType[] getEnumInfectiousAgentType() {
    return EnumInfectiousAgentType.values();
  }

  public void loadSymptoms() {
    symptoms = symptomService.getSymptoms();
  }

  public void loadResources() {
    resources = resourcesService.listResources();
  }

  public void createSymptom() {
    DTOSymptom dtoSymtom = new DTOSymptom();
    dtoSymtom.setName(symptomName);
    dtoSymtom.setDescription(symptomDescription);
    try {
      symptomService.newSymptom(dtoSymtom);
      symptoms.add(dtoSymtom);
      log.info("Se ha creado el sintoma.");
    } catch (EJBException | VirusControlException e) {
      log.error("Error: {}", e.getMessage());
    }
  }

  public void createDiseaseRequest() {
    DTODisease dtoDisease = new DTODisease();
    dtoDisease.setName(diseaseName);
    dtoDisease.setAgentName(agentName);
    dtoDisease.setAgentType(agentType);
    dtoDisease.setInfectionTime(infectionTime);
    dtoDisease.setRecommendedResources(selectedResources);
    dtoDisease.setSymptoms(selectedSymptoms);
    FacesContext context = FacesContext.getCurrentInstance();
    context.addMessage(null, new FacesMessage("Enfermedad creada", "La enfermedad ha sido creada exitosamente"));
    try {
      diseaseService.requestNewDisease(dtoDisease);
      log.info("Se ha creado el sintoma.");
    } catch (EJBException | VirusControlException e) {
      log.error("Error: {}", e.getMessage());
    }
  }

  public String capitalize(String string) {
    return string.substring(0, 1).toUpperCase() + string.substring(1).toLowerCase();
  }
}

backoffice/src/main/java/uy/viruscontrol/backoffice/ResourcesBean.java
package uy.viruscontrol.backoffice;

import java.io.Serializable;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import lombok.Getter;
import lombok.Setter;
import org.primefaces.PrimeFaces;
import uy.viruscontrol.business.service.ResourceService;
import uy.viruscontrol.common.dto.DTOResource;
import uy.viruscontrol.common.dto.DTOUpdateResource;
import uy.viruscontrol.common.enumerations.EnumResourceType;
import uy.viruscontrol.common.exceptions.VirusControlException;

@Named
@ViewScoped
@Getter
@Setter
public class ResourcesBean implements Serializable {
  @EJB
  private ResourceService resourceService;

  private String searchText = "";
  private DTOResource dtoResource = new DTOResource();
  private DTOUpdateResource dtoUpdateResource = new DTOUpdateResource();
  private DTOResource selectedResourceView = new DTOResource();
  private DTOResource selectedResourceUpdate = new DTOResource();
  private DTOResource selectedResourceDelete = new DTOResource();
  private List<String> resourceTypes;
  private List<DTOResource> resources;
  private List<DTOResource> resourcesCopy;

  @PostConstruct
  public void init() {
    resourceTypes =
      Arrays.stream(EnumResourceType.values()).map(enumResourceType -> capitalize(enumResourceType.name())).collect(Collectors.toList());
    resources = resourceService.listResources();
    resourcesCopy = resources;
  }

  public String capitalize(String string) {
    return string.substring(0, 1).toUpperCase() + string.substring(1).toLowerCase();
  }

  public void updateResource() {
    try {
      dtoUpdateResource.setName(selectedResourceUpdate.getName());
      dtoUpdateResource.setDescription(selectedResourceUpdate.getDescription());
      dtoUpdateResource.setResourceType(selectedResourceUpdate.getResourceType());
      resourceService.updateResource(selectedResourceUpdate.getId(), dtoUpdateResource);
      dtoUpdateResource = new DTOUpdateResource();
      dtoUpdateResource.setName("");
      dtoUpdateResource.setDescription("");
      resources = resourceService.listResources();
      resourcesCopy = resources;
      PrimeFaces current = PrimeFaces.current();
      current.executeScript("PF('updateResourceModal').hide();");
      FacesContext context = FacesContext.getCurrentInstance();
      context.addMessage(null, new FacesMessage("Recurso editado", "El recurso ha sido editado correctamente"));
    } catch (VirusControlException virusControlException) {
      FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Ocurrio un error.", null));
    }
  }

  public EnumResourceType[] getEnumResourceTypes() {
    return EnumResourceType.values();
  }

  public void newResource() {
    resourceService.newResource(this.dtoResource);
    dtoResource.setName("");
    dtoResource.setDescription("");
    resources = resourceService.listResources();
    resourcesCopy = resources;
    PrimeFaces current = PrimeFaces.current();
    current.executeScript("PF('addResourceModal').hide();");
    FacesContext context = FacesContext.getCurrentInstance();
    context.addMessage(null, new FacesMessage("Recurso creado", "El recurso ha sido creado exitosamente"));
  }

  public void deleteResource() {
    try {
      resourceService.deleteResource(selectedResourceDelete.getId());
      dtoResource.setName("");
      dtoResource.setDescription("");
      resources = resourceService.listResources();
      resourcesCopy = resources;
      PrimeFaces current = PrimeFaces.current();
      current.executeScript("PF('deleteResourceModal').hide();");
      FacesContext context = FacesContext.getCurrentInstance();
      context.addMessage(null, new FacesMessage("Recurso eliminado", "El recurso ha sido eliminado exitosamente"));
    } catch (VirusControlException virusControlException) {
      FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Ocurrio un error.", null));
    }
  }

  public void search() {
    if (searchText.isEmpty()) {
      resourcesCopy = resources;
    } else {
      resourcesCopy =
        resources.stream().filter(item -> item.getName().toLowerCase().contains(searchText.toLowerCase())).collect(Collectors.toList());
    }
  }
}

backoffice/src/main/java/uy/viruscontrol/backoffice/UserManagementBean.java
package uy.viruscontrol.backoffice;

import java.io.Serializable;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import lombok.Getter;
import lombok.Setter;
import org.primefaces.PrimeFaces;
import uy.viruscontrol.business.service.BackProfileService;
import uy.viruscontrol.common.dto.DTOBackProfile;
import uy.viruscontrol.common.dto.DTONewBackProfile;
import uy.viruscontrol.common.enumerations.EnumBackofficeUserRole;
import uy.viruscontrol.common.exceptions.VirusControlException;

@Named
@ViewScoped
@Getter
@Setter
public class UserManagementBean implements Serializable {
  @EJB
  BackProfileService backProfileService;

  private String searchText = "";
  private List<String> userRoles;
  private DTONewBackProfile dtoCreateProfile = new DTONewBackProfile();
  private DTONewBackProfile dtoUpdateProfile = new DTONewBackProfile();
  private DTOBackProfile selectedProfileEdit = new DTOBackProfile();
  private DTOBackProfile selectedProfileDelete = new DTOBackProfile();
  private List<DTOBackProfile> users;
  private List<DTOBackProfile> usersCopy;
  private static final String SOMETHING_HAPPENED = "Ocurrio un error.";

  @PostConstruct
  public void init() {
    userRoles =
      Arrays
        .stream(EnumBackofficeUserRole.values())
        .map(enumBackofficeUserRole -> capitalize(enumBackofficeUserRole.name()))
        .collect(Collectors.toList());
    users = backProfileService.listUsers();
    usersCopy = users;
  }

  public EnumBackofficeUserRole[] getEnumUserRoles() {
    return EnumBackofficeUserRole.values();
  }

  public String capitalize(String string) {
    return string.substring(0, 1).toUpperCase() + string.substring(1).toLowerCase();
  }

  public void search() {
    if (searchText.isEmpty()) {
      usersCopy = users;
    } else {
      usersCopy =
        users
          .stream()
          .filter(dtoBackProfile -> dtoBackProfile.getNickname().toLowerCase().contains(searchText.toLowerCase()))
          .collect(Collectors.toList());
    }
  }

  public void createProfile() {
    try {
      backProfileService.newProfile(this.dtoCreateProfile);
      dtoCreateProfile.setNickname("");
      dtoCreateProfile.setFullName("");
      dtoCreateProfile.setPassword("");
      dtoCreateProfile.setRole(null);
      users = backProfileService.listUsers();
      usersCopy = users;
      PrimeFaces current = PrimeFaces.current();
      current.executeScript("PF('addUserModal').hide();");
      FacesContext context = FacesContext.getCurrentInstance();
      context.addMessage(null, new FacesMessage("Usuario creado", "El usuario ha sido creado exitosamente"));
    } catch (VirusControlException virusControlException) {
      if (virusControlException.getCode().equals(2)) {
        FacesContext
          .getCurrentInstance()
          .addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Nickname duplicado", "Por favor ingrese otro nickname"));
      } else {
        FacesContext
          .getCurrentInstance()
          .addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, SOMETHING_HAPPENED, virusControlException.getMessage()));
      }
    }
  }

  public void updateProfile() {
    try {
      dtoUpdateProfile.setId(selectedProfileEdit.getId());
      dtoUpdateProfile.setNickname(selectedProfileEdit.getNickname());
      dtoUpdateProfile.setFullName(selectedProfileEdit.getFullName());
      dtoUpdateProfile.setRole(selectedProfileEdit.getRole());

      if (dtoUpdateProfile.getNickname() == null || dtoUpdateProfile.getNickname().equals("")) {
        dtoUpdateProfile.setNickname(selectedProfileEdit.getNickname());
      }

      if (dtoUpdateProfile.getFullName() == null || dtoUpdateProfile.getFullName().equals("")) {
        dtoUpdateProfile.setFullName(selectedProfileEdit.getFullName());
      }

      if (dtoUpdateProfile.getRole() == null) {
        dtoUpdateProfile.setRole(selectedProfileEdit.getRole());
      }

      backProfileService.updateUser(this.dtoUpdateProfile);

      dtoUpdateProfile.setFullName("");
      dtoUpdateProfile.setNickname("");
      dtoUpdateProfile.setPassword("");
      dtoUpdateProfile.setRole(null);
      users = backProfileService.listUsers();
      usersCopy = users;
      PrimeFaces current = PrimeFaces.current();
      current.executeScript("PF('modifyUserModal').hide();");
      FacesContext context = FacesContext.getCurrentInstance();
      context.addMessage(null, new FacesMessage("Usuario modificado", "El usuario ha sido modificado exitosamente"));
    } catch (VirusControlException virusControlException) {
      if (virusControlException.getCode().equals(2)) {
        FacesContext
          .getCurrentInstance()
          .addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Nickname duplicado", "Por favor ingrese otro nickname"));
      } else {
        FacesContext
          .getCurrentInstance()
          .addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, SOMETHING_HAPPENED, virusControlException.getMessage()));
      }
    }
  }

  public void deleteProfile() {
    try {
      backProfileService.delete(selectedProfileDelete.getId());
      users = backProfileService.listUsers();
      usersCopy = users;
      PrimeFaces current = PrimeFaces.current();
      current.executeScript("PF('deleteUserModal').hide();");
      FacesContext context = FacesContext.getCurrentInstance();
      context.addMessage(null, new FacesMessage("Usuario eliminado", "El usuario ha sido eliminado exitosamente"));
    } catch (VirusControlException virusControlException) {
      FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, SOMETHING_HAPPENED, null));
    }
  }
}

backoffice/src/main/webapp/app.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:c="http://java.sun.com/jsp/jstl/core">
<h:head>
    <title>VirusControl</title>
    <h:outputStylesheet name="primeicons/primeicons.css" library="primefaces"/>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="./resources/vendor/materialize.css"/>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
    <script src="./resources/vendor/materialize.js" type="text/javascript"></script>
    <script src="https://cdn.anychart.com/releases/8.7.1/js/anychart-core.min.js" type="text/javascript"></script>
    <script src="https://cdn.anychart.com/releases/8.7.1/js/anychart-map.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.3.15/proj4.js"></script>
    <script src="https://cdn.anychart.com/geodata/2.0.0/countries/uruguay/uruguay.js"></script>
</h:head>
<h:body style="overflow-y: hidden">
    <ui:debug hotkey="x" />
    <div style="height: calc(100vh);">
        <c:if test="#{navigationBean.logged eq true}">
            <c:if test="#{sessionBean.dtoBackProfile.role == 'SUPERVISOR'}">
                <ui:include src="/navbar.xhtml"/>
                <ui:include src="/dashboard.xhtml"/>
            </c:if>
            <c:if test="#{sessionBean.dtoBackProfile.role == 'ADMINISTRATOR'}">
                <ui:include src="/navbar.xhtml"/>
                <ui:include src="/dashboard.xhtml"/>
            </c:if>
        </c:if>
        <c:if test="#{navigationBean.logged eq false}">
            <ui:include src="/login.xhtml"/>
        </c:if>
    </div>
</h:body>
</html>

backoffice/src/main/webapp/requestNewDisease.xhtml
<ui:fragment
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:p="http://primefaces.org/ui"
        xmlns:f="http://java.sun.com/jsf/core"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:c="http://java.sun.com/jsp/jstl/core">

    <h:outputStylesheet library="css" name="requestNewDisease.css"/>

    <div class="container container">
        <h:form id="requestNewDiseaseForm">
            <div class="row">
                <div class="col s12">
                    <h3>Enfermedad</h3>
                </div>
                <div class="input-field col s12">
                    <p:inputText id="diseaseName" value="#{requestNewDiseaseBean.diseaseName}" label="Enfermedad" class="label-diseaseName"/>
                    <h:outputLabel for="diseaseName" value="Nombre"/>
                </div>
                <div class="input-field col s12 diseaseContainer">
                    <div class="input-field col s6">
                        <p:inputText type="number" id="diseaseInfectionTime" value="#{requestNewDiseaseBean.infectionTime}" label="Enfermedad" class="label-diseaseName"/>
                        <h:outputLabel for="diseaseInfectionTime" value="Tiempo de infeccion (dias)"/>
                    </div>
                </div>
                <div class="input-field col s12">
                    <h4>Agente</h4>
                </div>
                <div class="col s12 agentContainer">
                    <div class="input-field col s6" id="agentNameContainer" >
                        <p:inputText id="agentName" value="#{requestNewDiseaseBean.agentName}" label="Agente"/>
                        <h:outputLabel for="agentName" value="Nombre Agente"/>
                    </div>
                    <div class="col s6 selector-container">
                        <h:selectOneMenu value="#{requestNewDiseaseBean.agentType}">
                            <f:selectItem itemLabel="Tipo de Agente" itemValue=""/>
                            <f:selectItems var="item" value="#{requestNewDiseaseBean.enumInfectiousAgentType}" itemLabel="#{item.label}" itemValue="#{item}"/>
                        </h:selectOneMenu>
                    </div>
                </div>
                <div class="input-field col s12">
                    <h4>Sintoma</h4>
                </div>
                <div class="syntom-container col s12">
                    <div class="col s6 add-syntom-container">
                            <div class="input-field col s12">
                                <h5>Nuevo Sintoma</h5>
                            </div>
                            <div class="input-field col s12">
                                <p:inputText id="syntomName" value="#{requestNewDiseaseBean.symptomName}" label="Sintoma"/>
                                <h:outputLabel for="syntomName" value="Nombre Sintoma"/>
                            </div>
                            <div class="input-field col s12">
                                <h6>Descripcion de Sintoma</h6>
                                <br/>
                                <p:inputTextarea id="syntomDescription" value="#{requestNewDiseaseBean.symptomDescription}" placeholder="Descripcion de sintoma" rows="6" cols="33" />
                            </div>
                        <div class="col s12" id="create-syntom-button">
                            <p:commandLink value="Crear" class="waves-effect blue-grey lighten-2 btn" style="margin-right:20px; !important;" action="#{requestNewDiseaseBean.createSymptom}" update=":requestNewDiseaseForm:syntoms-display"/>
                        </div>
                    </div>
                    <div class="col s6 show-syntom-container">
                        <div class="col s12" style="padding-top: 15px !important;">
                            <h5>Sintomas disponibles</h5>
                        </div>
                        <div class="input-field col s12" id="checkbox">
                            <p:selectManyMenu id="syntoms-display" value="#{requestNewDiseaseBean.selectedSymptoms}" converter="NewDiseaseConverter"
                                              var="s" filter="true" filterBy="#{requestNewDiseaseBean.symptoms.name}" filterMatchMode="contains" showCheckbox="true">
                                <c:if test="#{requestNewDiseaseBean.symptoms == null}">
                                    <p:column style="border-spacing: 10px!important;">
                                        <h:outputText value="No hay sintomas" />
                                    </p:column>
                                </c:if>
                                <f:selectItems value="#{requestNewDiseaseBean.symptoms}" var="syntoms" itemLabel="#{syntoms.name}" itemValue="#{syntoms}" />
                                <p:column style="border-spacing: 10px!important;">
                                    <h:outputText value="#{s.name}" />
                                </p:column>
                            </p:selectManyMenu>
                        </div>
                    </div>
                </div>

                <div class="input-field col s12" style="padding-top: 15px !important;">
                    <h4>Recursos</h4>
                </div>
                <div class="syntom-container col s12">

                    <div class="col s12" style="padding-top: 15px !important;">
                        <h5>Recursos disponibles</h5>
                    </div>
                    <div class="input-field col s12" id="checkboxResources">
                        <p:selectManyMenu id="resources-display" value="#{requestNewDiseaseBean.selectedResources}" converter="NewResourceConverter"
                                          var="r" filter="true" filterBy="#{requestNewDiseaseBean.resources.name}" filterMatchMode="contains" showCheckbox="true">
                            <f:selectItems value="#{requestNewDiseaseBean.resources}" var="resources" itemLabel="#{resources.name}" itemValue="#{resources}" />
                            <p:column style="border-spacing: 10px!important;">
                                <h:outputText value="#{r.name}" />
                            </p:column>
                        </p:selectManyMenu>
                    </div>
                </div>

                <div class="col s12" style="padding-top: 100px !important; text-align: center !important;">
                    <p:growl id="growlConfirm" showDetail="true" sticky="false" life="2000" />
                    <p:commandLink value="Confirmar" class="waves-effect blue-grey btn" style="margin-right:80px !important;" action="#{requestNewDiseaseBean.createDiseaseRequest}" update="@form" onclick="handleReload()"/>
                </div>
            </div>
        </h:form>
    </div>
    <script>
        $(document).ready(function () {
            $('select').formSelect();
        });
        function handleReload () {
            setTimeout(() => {
                location.reload();
            }, 2000)
        }
    </script>
</ui:fragment>